"""GitHub PR comment helpers — no network; exercise marker + wrap logic."""

from focus.ci.github_comment import FOCUS_COMMENT_MARKER, render_pr_comment


def test_render_pr_comment_adds_marker_and_footer():
    body = render_pr_comment("## Focus\n\n**LOW** risk.")
    assert FOCUS_COMMENT_MARKER in body
    assert "## Focus" in body
    assert "Generated by Focus" in body


def test_render_pr_comment_idempotent_marker():
    once = render_pr_comment("## Focus\n")
    twice = render_pr_comment(once)
    assert twice.count(FOCUS_COMMENT_MARKER) == 1
